# -*- coding: utf-8 -*-
"""ninibo1127

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zxr-BSuHIRDOyN7QioA4lsa5uSHmm0o9
"""

import os

# ① 環境変数をファイルから読み込む関数
def load_env_from_file(filename):
    with open(filename) as f:
        for line in f:
            if '=' in line:
                key, value = line.strip().split('=', 1)
                os.environ[key] = value

# ② 読み込むファイルを指定
load_env_from_file("config.env")  # または "keys.log"

# ③ 読み込んだ環境変数を使う
api_key = os.getenv("API_KEY")
secret_key = os.getenv("SECRET_KEY")

import ccxt

# bitbankの取引所インスタンスを作成
bitbank = ccxt.bitbank()

try:
    # ロードマーケット情報
    bitbank.load_markets()

    # BTC/JPYペアの情報から最低取引数量を取得
    # 'limits'->'amount'->'min' のパスで取得できることが多い
    # 取引所によってはこの構造が異なる場合があります
    min_amount = bitbank.markets['BTC/JPY']['limits']['amount']['min']

    print(f"bitbank (BTC/JPY) の最低取引数量は {min_amount} BTC です。")

except ccxt.base.errors.ExchangeError as e:
    print(f"取引所エラーが発生しました: {e}")
except KeyError:
    print("必要な情報 (最低取引数量) が取引所情報に見つかりませんでした。")
    print("bitbankのAPIドキュメントを確認してください。")
except Exception as e:
    print(f"エラーが発生しました: {e}")

from dotenv import load_dotenv
import os

load_dotenv(dotenv_path='config.env')  # ← 変更後のファイル名に合わせてるよ

api_key = os.getenv("API_KEY")
secret_key = os.getenv("SECRET_KEY")

print("API_KEY:", api_key)
print("SECRET_KEY:", secret_key)

import ccxt
import pandas as pd
import time
import os
import datetime
import pytz
import math # mathモジュールを追加

# 日本標準時 (JST) のタイムゾーンオブジェクトを作成
JST = pytz.timezone('Asia/Tokyo')

# === 1. 取引所への接続 ===
def connect_to_bitbank():
    """bitbankに接続します"""
    try:
        # 🔑 dotenvで読み込んだキーを直接使用
        from dotenv import load_dotenv # 関数内で再度インポート

        # 読み込みのパスは既に実行されているはずですが、念のため
        load_dotenv(dotenv_path='config.env')

        # dotenvで読み込んだ変数名 (API_KEY, SECRET_KEY) に合わせてキーを取得
        api_key = os.getenv("API_KEY")
        secret_key = os.getenv("SECRET_KEY")

        # デバッグ用: 取得したキーの一部を表示
        print(f"DEBUG: API Key (partial): {api_key[:4]}...{api_key[-4:]}" if api_key else "DEBUG: API Key: None")
        print(f"DEBUG: Secret Key (partial): {secret_key[:4]}...{secret_key[-4:]}" if secret_key else "DEBUG: Secret Key: None")


        if not api_key or not secret_key:
            print("エラー：config.envからAPIキーが読み込まれていません。")
            return None

        # ccxtを使ってbitbankに接続
        exchange = ccxt.bitbank({
            'apiKey': api_key, # 修正後の変数名を使用
            'secret': secret_key, # 修正後の変数名を使用
        })
        print("bitbankにccxtで接続しました。")
        return exchange

    except Exception as e:
        print(f"bitbankへの接続中にエラーが発生しました: {e}")
        return None



        if not api_key or not secret_key:
            print("エラー：APIキーが設定されていません。環境変数を確認してください。")
            return None

        # ccxtを使ってbitbankに接続
        exchange = ccxt.bitbank({
            'apiKey': api_key,
            'secret': secret_key,
        })
        print("bitbankにccxtで接続しました。")
        return exchange

    except Exception as e:
        print(f"bitbankへの接続中にエラーが発生しました: {e}")
        return None

# === 2. 価格データの取得 ===
def get_ohlcv(exchange, pair='BTC/JPY', timeframe='1h', limit=250):
    """
    指定した通貨ペアのOHLCVデータを取得します。(ccxt使用)
    """
    try:
        ohlcv_data = exchange.fetch_ohlcv(pair, timeframe, limit=limit)

        if ohlcv_data:
            # データをDataFrameに変換
            df = pd.DataFrame(ohlcv_data, columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])
            df['timestamp'] = pd.to_datetime(df['timestamp'], unit='ms')
            df = df.set_index('timestamp')
            return df
        else:
            print(f"{pair} のOHLCVデータを取得できませんでした。")
            return None

    except Exception as e:
        print(f"OHLCVデータの取得中にエラーが発生しました: {e}")
        return None

# === 3. 売買シグナルの判定（MA 25/75/200 + 買い増しロジック） ===
def generate_signals(df):
    """
    価格データに基づいて売買シグナルを生成します。
    """
    # データ数が200本必要
    if df is None or len(df) < 200:
        print(f"DEBUG: データが不足しています。最低200本必要ですが、{len(df)}本しかありません。")
        return None

    # 短期25、中期75、長期200を追加
    df['short_mavg'] = df['close'].rolling(window=25).mean()
    df['mid_mavg'] = df['close'].rolling(window=75).mean() # 75をmidに名称変更
    df['long_mavg'] = df['close'].rolling(window=200).mean() # 新しい長期MA

    latest_data = df.iloc[-1]
    previous_data = df.iloc[-2]
    signal = None

    # 🔑 トレンドフィルター
    is_uptrend = latest_data['mid_mavg'] > latest_data['long_mavg']
    mid_mavg_is_rising = latest_data['mid_mavg'] > previous_data['mid_mavg']

    # --- 買いシグナル 1：新規エントリー (ゴールデンクロス) ---
    if (previous_data['short_mavg'] <= previous_data['mid_mavg'] and
        latest_data['short_mavg'] > latest_data['mid_mavg'] and
        is_uptrend and mid_mavg_is_rising):
        signal = 'buy_entry' # 新規エントリーシグナル
        print("✅ 新規エントリーシグナル (GC 25/75、トレンド確認) が発生しました。")

    # --- 買いシグナル 2：買い増し (押し目) ---
    elif latest_data['close'] > latest_data['short_mavg'] and is_uptrend:
        signal = 'buy_add' # 買い増しシグナル
        print("📈 買い増しシグナル (押し目買い) が発生しました。")

    # --- 売りシグナル：全決済 (トレンド終了) ---
    # MA75がMA200を下回った、またはMA75が下向きに転じた
    elif not is_uptrend or latest_data['mid_mavg'] < previous_data['mid_mavg']:
        signal = 'sell_all'
        print("❌ 全決済シグナル (長期トレンド終了/反転) が発生しました。")

    return signal

# === 4. 注文の実行 ===
def execute_order(exchange, pair, order_type, amount, price=None):
    """
    bitbankに注文を出します。(ccxt使用)
    """
    try:
        # ccxtのcreate_orderメソッドを使用
        if order_type == 'buy':
            type = 'limit' if price else 'market'
            order = exchange.create_order(pair, type, 'buy', amount, price)
            print(f"{type} 買い注文を発注しました: {amount:.4f} {pair.split('/')[0]} {'@ ' + str(price) if price else ''}")
        elif order_type == 'sell':
            type = 'limit' if price else 'market'
            order = exchange.create_order(pair, type, 'sell', amount, price)
            print(f"{type} 売り注文を発注しました: {amount:.4f} {pair.split('/')[0]} {'@ ' + str(price) if price else ''}")
        else:
            print(f"無効な注文タイプです: {order_type}")
            return None

        if order:
            print("注文成功:", order)
            return order
        else:
            print("注文に失敗しました:", order)
            return None

    except Exception as e:
        print(f"注文実行中にエラーが発生しました: {e}")
        return None

# === 5. メインループ（Botの実行部分） ===
# 🔑 修正: APIキーとシークレットキーを受け取る引数を追加
def run_bot(pair='BTC/JPY', interval_seconds=3600, api_key=None, secret_key=None):
    """
    自動売買Botのメイン実行ループです。(ccxt使用)
    """
    # 🔑 修正: 接続関数にキーを渡すように変更
    exchange = connect_to_bitbank(api_key, secret_key)
    if not exchange:
        print("API接続に失敗したためBotを停止します。")
        return

    print(f"Botを {pair} で実行します。データ取得間隔: {interval_seconds}秒")

    # --- 🔑【初期設定】注文数量の計算と最低注文単位のチェック ---

    # 1. 予算と最低取引単位の設定
    JAPANESE_YEN_BUDGET = 10000 # 1回の注文に使う日本円の予算: 10,000円
    MIN_ORDER_BTC = 0.001 # bitbank BTC/JPYの最低注文量（ここが将来的に変わる可能性あり）
    print(f"💰 1回あたりの注文予算: {JAPANESE_YEN_BUDGET} 円")
    print(f"📉 最低注文数量: {MIN_ORDER_BTC} BTC")

    # 2. 最新の市場価格を取得
    try:
        ticker = exchange.fetch_ticker(pair)
        latest_price = ticker['last']
        print(f"💵 最新の市場価格: {latest_price} 円")
    except Exception as e:
        print(f"エラー: 最新価格の取得に失敗しました。Botを停止します: {e}")
        return

    # 3. 注文数量を計算 (予算 ÷ 価格)
    buy_amount_per_order_raw = JAPANESE_YEN_BUDGET / latest_price
    # 最小取引単位（0.0001 BTC）に合わせて切り捨てる
    buy_amount_per_order = math.floor(buy_amount_per_order_raw * 10000) / 10000

    # 4. 【安全チェック】予算が最低注文量を下回ったか確認
    if buy_amount_per_order < MIN_ORDER_BTC:
         print("---------------------------------------------------------")
         print("🚨 致命的な警告: 予算見直しが必要です！")
         print(f"現在の予算({JAPANESE_YEN_BUDGET}円)では、最低注文量({MIN_ORDER_BTC} BTC)を")
         print(f"満たせません。現在の計算量: {buy_amount_per_order:.4f} BTC")
         print("将来の価格高騰に備え、`JAPANESE_YEN_BUDGET`を増額してください。Botを停止します。")
         print("---------------------------------------------------------")
         return

    print(f"🛒 1回あたりの注文数量: {buy_amount_per_order:.4f} BTC")

    # -----------------------------------------------------

    timeframe = '1h'
    data_limit = 250

    while True:
        try:
            print("Bot loop iteration started.")

            # --- 🔑【追加】ポジションの正確な取得 ---
            # ループの最初にAPIから残高を取得し、Botの記憶を現実に合わせる
            try:
                balance = exchange.fetch_balance()
                # BTCの保有量を正確に取得 (キーは取引所とccxtのバージョンにより異なる可能性あり)
                current_position_amount = balance['total']['BTC']
                print(f"✅ APIから取得した正確な保有数量: {current_position_amount} BTC")
            except Exception as e:
                print(f"⚠️ エラー: 残高の取得に失敗しました。取引をスキップします: {e}")
                time.sleep(interval_seconds)
                continue
            # ------------------------------------

            # 現在の日付と時刻を取得 (JST)
            now_utc = datetime.datetime.now(datetime.timezone.utc)
            now_jst = now_utc.astimezone(JST)
            weekday = now_jst.weekday() # 月曜日が0、日曜日が6

            # 土曜日 (5) または日曜日 (6) でない場合はスキップ
            if weekday < 5:
                print(f"現在時刻 (JST): {now_jst.strftime('%Y-%m-%d %H:%M:%S')} - 平日なので取引をスキップします。")
                time.sleep(interval_seconds)
                continue

            print(f"現在時刻 (JST): {now_jst.strftime('%Y-%m-%d %H:%M:%S')} - 週末なので取引を実行します。")

            # 2. 価格データの取得: 1時間足データを250本取得
            ohlcv_df = get_ohlcv(exchange, pair, timeframe=timeframe, limit=data_limit)

            if ohlcv_df is not None and not ohlcv_df.empty:
                # 3. 売買シグナルの判定（25/75/200 MA）
                signal = generate_signals(ohlcv_df)

                # --- 🔑 損切りロジックの判定と実行 ---
                if current_position_amount > 0.0:
                    latest_close = ohlcv_df.iloc[-1]['close']
                    # 中期MA(75)を損切りラインとして使用
                    mid_mavg = ohlcv_df.iloc[-1]['mid_mavg']

                    if latest_close < mid_mavg:
                        print(f"🚨 損切りシグナル！終値({latest_close})が中期MA({mid_mavg})を下回りました。")

                        # 損切りを実行（保有数量を全量売り）
                        sell_amount = current_position_amount
                        order_result = execute_order(exchange, pair, 'sell', sell_amount, price=None)

                        if order_result:
                            print("🔥 買いポジションを損切りにより全量解消しました。次のループで残高を確認します。")
                        else:
                            print("⚠️ 損切り注文に失敗しました。")


                # --- 4. 注文の実行 (エントリー/買い増し/全決済) ---

                # 買いシグナル 1：新規エントリー (buy_entry)
                if signal == 'buy_entry' and current_position_amount == 0.0:
                    order_result = execute_order(exchange, pair, 'buy', buy_amount_per_order, price=None)

                # 買いシグナル 2：買い増し (buy_add)
                elif signal == 'buy_add' and current_position_amount > 0.0:
                    order_result = execute_order(exchange, pair, 'buy', buy_amount_per_order, price=None)

                # 売りシグナル：全決済 (sell_all)
                elif signal == 'sell_all' and current_position_amount > 0.0:
                    # 全量売り（利確）
                    sell_amount = current_position_amount
                    order_result = execute_order(exchange, pair, 'sell', sell_amount, price=None)

                # ロジックの実行状況を表示
                print(f"現在のシグナル: {signal}, API取得の正確な保有数量: {current_position_amount} BTC")

            else:
                print("データ取得に失敗したため、次のループに進みます。")

        except Exception as e:
            print(f"Bot実行中にエラーが発生しました: {e}")

        # 指定された間隔で待機
        print(f"次回の実行まで {interval_seconds}秒待機します...")
        time.sleep(interval_seconds)

# Botを実行
if __name__ == "__main__":
  　# 🔑 修正: run_botに最上部で定義したキーを渡す
    run_bot('BTC/JPY', 3600, API_KEY, SECRET_KEY)

"""# Task
CONOHA VPS上で、現在Colabで動作しているBotを動作させる。

## Conoha vpsのセットアップ

### Subtask:
CONOHA VPSを契約し、OS（例: Ubuntu）をインストールし、SSHで接続できるようにします。

## 必要なソフトウェアのインストール

### Subtask:
VPSにPython、pip、そしてBotが必要とするライブラリ（ccxt, pandas, pytz）をインストールします。

## Botコードの転送

### Subtask:
現在のColab notebookからBotのPythonコードをVPSに転送します。

## Apiキーの設定

### Subtask:
Colabのシークレットマネージャーではなく、VPS上で安全な方法（環境変数など）でAPIキーを設定します。

## Botの実行

### Subtask:
VPS上でBotのPythonスクリプトを実行します。永続的に実行するために、`screen`や`tmux`、またはsystemdなどのツールを使用することを検討します。

## 監視とログ

### Subtask:
Botが正常に動作しているか監視し、問題発生時にデバッグできるようログを設定します。

## Summary:

### Data Analysis Key Findings

* The entire process of migrating the bot from Colab to CONOHA VPS involves several steps that require manual interaction with the VPS environment, including setting up the VPS, installing software, transferring code, configuring API keys, executing the bot, and monitoring/logging.
* The current execution environment (Jupyter Notebook/Colab) does not support the necessary operations, such as SSH connections, remote file system interaction, and executing commands directly on the VPS.
* Consequently, none of the sub-tasks could be completed programmatically within the notebook environment.

### Insights or Next Steps

* The migration process requires direct access to and interaction with the CONOHA VPS via SSH.
* The user needs to perform the steps manually or use tools outside the Colab environment to complete the bot migration.
"""